Repository Spikeysanju/Expenso, pull requests merged in 2021-02, with the labels that each got.

#25 Update README.MD
  LICENSE
  README.md
Labels: documentation

#27 Add Empty State #26
  app/src/main/java/dev/spikeysanju/expensetracker/MainActivity.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/AddTransactionFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/DashboardFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/EditTransactionFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/TransactionDetailsFragment.kt
  app/src/main/res/layout/content_empty_state_layout.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/raw/empty.json
  app/src/main/res/values/strings.xml
Labels: enhancement

#30 Refactor Overall
  app/build.gradle
  app/src/main/java/dev/spikeysanju/expensetracker/utils/TextInputDropDownMenu.kt
  app/src/main/java/dev/spikeysanju/expensetracker/utils/viewState/DetailState.kt
  app/src/main/java/dev/spikeysanju/expensetracker/utils/viewState/ViewState.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/adapter/TransactionAdapter.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/add/AddTransactionFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/base/BaseFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/dashboard/DashboardFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/details/TransactionDetailsFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/main/viewmodel/TransactionViewModel.kt
  app/src/main/res/layout/content_add_transaction_layout.xml
  app/src/main/res/layout/content_income_expense_card_layout.xml
  app/src/main/res/layout/error_dialog_layout.xml
  app/src/main/res/layout/fragment_dashboard.xml
  app/src/main/res/layout/fragment_transaction_details.xml
  app/src/main/res/layout/item_transaction_layout.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: improvements

#34 Fix save transaction
  app/src/main/java/dev/spikeysanju/expensetracker/utils/ViewExt.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/add/AddTransactionFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/edit/EditTransactionFragment.kt
Labels: bug

#36 Refactor AboutFragment.kt & AboutViewModel.kt #35
  app/src/main/java/dev/spikeysanju/expensetracker/view/about/AboutFragment.kt
  app/src/main/java/dev/spikeysanju/expensetracker/view/about/AboutViewModel.kt
  app/src/main/res/layout/fragment_about.xml
Labels: improvements

#43 :memo: added build tools section
  .idea/runConfigurations.xml
  README.md
  beta_android.png
Labels: documentation

#45 Update README.md
  README.md
Labels: documentation

#46 Setup docsify
  .idea/runConfigurations.xml
  docs/.nojekyll
  docs/README.md
  docs/index.html
  docs/pages/_sidebar.md
  docs/pages/add-architecture.md
  docs/pages/changelog.md
  docs/pages/design.md
  docs/pages/endnote.md
  docs/pages/overview.md
  docs/pages/setup-project.md
Labels: documentation
